### ISSUE TITLE
redirect for trailing slash

### ISSUE THREAD

**Issue by wighawag** [lwsjs/redirect#3]
Hi, I am trying to get redirect of url like `http://localhost:8000/dist` to `http://localhost:8000/dist/`

Basically I want to redirect to trailing slash url, but I can not figure out how to do it. I tried several regex but none of them work. Any idea ?

**Comment by wighawag** [comment]
Actually it need to be more than a simple regex since I need to detect folder vs files.

Did a middleware js instead :https://github.com/wighawag/routify-test-ipfs/blob/9a473a003239c5bf91c918a313c197623dd96cea/trailing-slash.js

Very nice middleware system!

**Comment by 75lb** [comment]
If you are you looking to serve a directory listing page, use [lws-index](https://github.com/lwsjs/index) - it handles the `dist` -> `dist/` redirect for you. This is typically used alongside [lws-static](https://github.com/lwsjs/static) to serve static directories and files. 

```
$ npm install lws lws-static lws-index
$ lws --stack static index
```

**Comment by 75lb** [comment]
Well done creating your own middleware! This is the most powerful solution since you have complete control.. 

You're right, you cannot test whether a directory exists at a given path with a redirect rule alone. 

However, I'll add a `--redirect.test` option to the redirect module to make it easier to test out redirect rules against the given config.

**Comment by wighawag** [comment]
hmm, I am using `local-web-server` and tried with `yarn ws --stack static index` but it did not redirect to trailing slash

**Comment by 75lb** [comment]
with local-web-server, both `/dist` and `/dist/` will do the same thing - display a directory listing for the `dist` folder.. 

What's your OS, Node.js version and ws version?

**Comment by wighawag** [comment]
I know that this will point to the same content but I need the "redirect to trailing slash" to emulate a specific environment under which my app will be deployed

**Comment by wighawag** [comment]
In particular in how it affect relative urls

**Comment by 75lb** [comment]
Does a simple rewrite rule not cut the mustard? E.g. this will redirect `yeah` to `yeah/`:

```
$ npm install --save-dev lws-redirect
$ ws --stack redirect static index --redirect 'yeah -> yeah/'
$ curl http://127.0.0.1:8000/yeah -I
HTTP/1.1 302 Found
Location: http://127.0.0.1:8000/yeah/
Content-Type: text/html; charset=utf-8
Content-Length: 85
Date: Sat, 23 May 2020 08:07:40 GMT
Connection: keep-alive
```

**Comment by wighawag** [comment]
I fixed the issue with my script.
The simple rule you mentioned would only work for yeah.
And a generic rule will append slash to files (I want only folders)

**Comment by 75lb** [comment]
No problem. Well, to make developing redirect rules easier I added a debugging tool to the package, [details here](https://github.com/lwsjs/redirect#debugging).
